baseURL = 'https://phedayat.com/'
languageCode = 'en-us'
title = 'ph'
theme = 'hugo-classic'
description = 'My speck of the internet'

[params]
footer = ''

[markup.highlight]
# style = "catppuccin-mocha"
style = "modus-vivendi"
# style = "onedark"
# style = "rose-pine"

[markup.goldmark.renderer]
unsafe = true
xhtml = true